Feature/arrays
xevyd/study pull request #3
Opened 2020-04-20 11:16 UTC by xevyd

fix

2020-04-20 17:05 UTC, artempartos requested changes

2020-04-20 17:05 UTC, artempartos commented on test/exercise/arrays/solution.rb
>        def search(_array, _query)
в руби есть соглашение что _ перед переменной означает что переменная не используется, у тебя array используется, переименуй

2020-04-20 17:05 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +          while first <= last
давай реализуем через рекурсивный подход

2020-04-21 13:24 UTC, xevyd commented on test/exercise/arrays/solution.rb
>        def search(_array, _query)
поправил

2020-04-21 13:25 UTC, xevyd commented on test/exercise/arrays/solution.rb
> +          while first <= last
сделал

2020-04-23 10:35 UTC, devality approved these changes

2020-04-23 10:55 UTC, merged