fp2
xevyd/study pull request #5
Opened 2020-04-22 10:26 UTC by xevyd

2020-04-23 10:40 UTC, devality requested changes

2020-04-23 10:40 UTC, devality commented on test/exercise/fp2/solution.rb
> +        self.my_each { |el| result << el unless el.nil? }
Теперь давай попробуем реализовать my_map и my_compact через my_reduce потому что он подойдет сюда еще лучше чем my_each.

2020-04-23 14:24 UTC, xevyd commented on test/exercise/fp2/solution.rb
> +        self.my_each { |el| result << el unless el.nil? }
переделал

2020-04-25 19:13 UTC, Andrew8xx8 approved these changes

2020-04-25 19:25 UTC, merged