rackup
xevyd/study pull request #6
Opened 2020-04-22 17:52 UTC by xevyd

2020-04-25 19:14 UTC, Andrew8xx8 commented
Добавь еще пример использования метода `post`. Нужно дописать тест, и myapp.

2020-04-26 06:36 UTC, xevyd commented
добавил post

2020-04-29 11:57 UTC, Andrew8xx8 requested changes

2020-04-29 11:57 UTC, Andrew8xx8 commented on test/exercise/rackup/inatra.rb
> +      method = method_name.to_s
Нужно еще добавить обработку ситуации когда для метод и пути не определен роут в `Inatra.routes do` 

Ответ должен быть 
```
[404, {}, 'Not Found']
```

2020-04-30 12:32 UTC, xevyd commented
добавил новые тесты

2020-04-30 12:41 UTC, Andrew8xx8 requested changes

2020-04-30 12:41 UTC, Andrew8xx8 commented on test/exercise/rackup/test.rb
> +    browser.post '/hello'
Одна проверка на один тест должна быть, а тут две в одном тесте.

Скопируй просто тесты из оригинального репозитория

2020-04-30 12:46 UTC, xevyd commented on test/exercise/rackup/test.rb
> +    browser.post '/hello'
перемудрил с гитом, видимо. поправил

2020-04-30 21:43 UTC, Andrew8xx8 approved these changes

2020-05-01 06:58 UTC, merged